In [1]:
import numpy as np

In [8]:
test_arr = np.array([[10]*10] * 10)

In [9]:
test_arr

array([[10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10, 10, 10]])

In [12]:
norm = np.linalg.norm(test_arr, axis=-1)

In [13]:
norm

array([31.6227766, 31.6227766, 31.6227766, 31.6227766, 31.6227766,
       31.6227766, 31.6227766, 31.6227766, 31.6227766, 31.6227766])

In [16]:
test = test_arr[:, -1] / norm

In [17]:
test

array([0.31622777, 0.31622777, 0.31622777, 0.31622777, 0.31622777,
       0.31622777, 0.31622777, 0.31622777, 0.31622777, 0.31622777])